apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: task-pv-dep-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pv-pod-app
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim-1
      containers:
        - name: task-pv-container-1
          image: rahulalishetty/cont1-2:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/data"
              name: task-pv-storage